from PyQt6 import QtCore, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QPainter, QColor, QPen
from PyQt6.QtWidgets import QLabel, QCheckBox


class UiClass(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("main_widget")
        self.width = 900
        self.height = 420
        mainWidget.resize(900, 610)
        self.secondWidget = QtWidgets.QWidget(mainWidget)
        self.secondWidget.setObjectName("second_widget")

        self.pushButton = QtWidgets.QPushButton(self.secondWidget)
        self.pushButton.setGeometry(QtCore.QRect(98, 350, 101, 41))
        self.pushButton.setObjectName("start_test")

        self.pushButton2 = QtWidgets.QPushButton(self.secondWidget)
        self.pushButton2.setGeometry(QtCore.QRect(28, 300, 101, 41))
        self.pushButton2.setObjectName("select_file")

        self.pushButton3 = QtWidgets.QPushButton(self.secondWidget)
        self.pushButton3.setGeometry(QtCore.QRect(168, 300, 101, 41))
        self.pushButton3.setObjectName("generate_random")

        self.label_1 = QLabel(self.secondWidget)
        self.label_1.setGeometry(QtCore.QRect(350, 20, 150, 20))
        self.label_1.setObjectName("label_1")
        self.textEdit_1 = QtWidgets.QTextEdit(self.secondWidget)
        self.textEdit_1.setGeometry(QtCore.QRect(350, 40, 530, 350))
        self.textEdit_1.setObjectName("textEdit_1")
        self.label_2 = QLabel(self.secondWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 410, 150, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.secondWidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 430, 860, 150))
        self.textEdit_2.setObjectName("textEdit_2")

        self.check_boxes = []
        # 15个选择按钮
        self.checkbtn_1 = QCheckBox(self.secondWidget)
        self.checkbtn_1.setGeometry(QtCore.QRect(10, 25, 120, 30))
        self.checkbtn_1.setObjectName("chekbtn_1")
        self.check_boxes.append(self.checkbtn_1)
        self.checkbtn_2 = QCheckBox(self.secondWidget)
        self.checkbtn_2.setGeometry(QtCore.QRect(120, 25, 120, 30))
        self.checkbtn_2.setObjectName("chekbtn_2")
        self.check_boxes.append(self.checkbtn_2)
        self.checkbtn_3 = QCheckBox(self.secondWidget)
        self.checkbtn_3.setGeometry(QtCore.QRect(230, 25, 120, 30))
        self.checkbtn_3.setObjectName("chekbtn_3")
        self.check_boxes.append(self.checkbtn_3)
        self.checkbtn_4 = QCheckBox(self.secondWidget)
        self.checkbtn_4.setGeometry(QtCore.QRect(10, 75, 120, 30))
        self.checkbtn_4.setObjectName("chekbtn_4")
        self.check_boxes.append(self.checkbtn_4)
        self.checkbtn_5 = QCheckBox(self.secondWidget)
        self.checkbtn_5.setGeometry(QtCore.QRect(120, 75, 120, 30))
        self.checkbtn_5.setObjectName("chekbtn_5")
        self.check_boxes.append(self.checkbtn_5)
        self.checkbtn_6 = QCheckBox(self.secondWidget)
        self.checkbtn_6.setGeometry(QtCore.QRect(230, 75, 120, 30))
        self.checkbtn_6.setObjectName("chekbtn_6")
        self.check_boxes.append(self.checkbtn_6)
        self.checkbtn_7 = QCheckBox(self.secondWidget)
        self.checkbtn_7.setGeometry(QtCore.QRect(10, 125, 120, 30))
        self.checkbtn_7.setObjectName("chekbtn_7")
        self.check_boxes.append(self.checkbtn_7)
        self.checkbtn_8 = QCheckBox(self.secondWidget)
        self.checkbtn_8.setGeometry(QtCore.QRect(120, 125, 120, 30))
        self.checkbtn_8.setObjectName("chekbtn_8")
        self.check_boxes.append(self.checkbtn_8)
        self.checkbtn_9 = QCheckBox(self.secondWidget)
        self.checkbtn_9.setGeometry(QtCore.QRect(230, 125, 120, 30))
        self.checkbtn_9.setObjectName("chekbtn_9")
        self.check_boxes.append(self.checkbtn_9)
        self.checkbtn_10 = QCheckBox(self.secondWidget)
        self.checkbtn_10.setGeometry(QtCore.QRect(10, 175, 120, 30))
        self.checkbtn_10.setObjectName("chekbtn_10")
        self.check_boxes.append(self.checkbtn_10)
        self.checkbtn_11 = QCheckBox(self.secondWidget)
        self.checkbtn_11.setGeometry(QtCore.QRect(120, 175, 120, 30))
        self.checkbtn_11.setObjectName("chekbtn_11")
        self.check_boxes.append(self.checkbtn_11)
        self.checkbtn_12 = QCheckBox(self.secondWidget)
        self.checkbtn_12.setGeometry(QtCore.QRect(230, 175, 120, 30))
        self.checkbtn_12.setObjectName("chekbtn_12")
        self.check_boxes.append(self.checkbtn_12)
        self.checkbtn_13 = QCheckBox(self.secondWidget)
        self.checkbtn_13.setGeometry(QtCore.QRect(10, 225, 120, 30))
        self.checkbtn_13.setObjectName("chekbtn_13")
        self.check_boxes.append(self.checkbtn_13)
        self.checkbtn_14 = QCheckBox(self.secondWidget)
        self.checkbtn_14.setGeometry(QtCore.QRect(120, 225, 120, 30))
        self.checkbtn_14.setObjectName("chekbtn_14")
        self.check_boxes.append(self.checkbtn_14)
        # self.checkbtn_15 = QCheckBox(self.secondWidget)
        # self.checkbtn_15.setGeometry(QtCore.QRect(230, 225, 100, 30))
        # self.checkbtn_15.setObjectName("chekbtn_15")
        # self.check_boxes.append(self.checkbtn_15)


        mainWidget.setCentralWidget(self.secondWidget)

        # 重新翻译一遍UI，是一个动态翻译的解决方案。
        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidgets):
        _translate = QtCore.QCoreApplication.translate
        mainWidgets.setWindowTitle("密码学课设2021214519")
        self.pushButton.setText("开始测试")
        self.pushButton2.setText("选择文件")
        self.pushButton3.setText("随机生成")
        self.label_1.setText("文本序列：")
        self.label_2.setText("检测结果：")
        self.checkbtn_1.setText("单比特频数检测")
        self.checkbtn_2.setText("块内频数检测")
        self.checkbtn_3.setText("扑克检测")
        self.checkbtn_4.setText("重叠子序列检测")
        self.checkbtn_5.setText("游程检测")
        self.checkbtn_6.setText("块内最大游程")
        self.checkbtn_7.setText("二元推导检测")
        self.checkbtn_8.setText("自相关检测")
        self.checkbtn_9.setText("矩阵秩检测")
        self.checkbtn_10.setText("累加和检测")
        self.checkbtn_11.setText("近似熵检测")
        self.checkbtn_12.setText("线性复杂度检测")
        self.checkbtn_13.setText("Maurer通用统计")
        self.checkbtn_14.setText("离散傅里叶检测")
        # self.checkbtn_1.setText("单比特频数")
